### ISSUE TITLE
Add HMR to documentation

### ISSUE THREAD

**Issue by elevatebart** [znck/preview#7]
## Reproduction

1. Run `pnpm start` to start the preview server
1. Navigate to the `input` component
1. Open the docs panel on the right for `input.vue`
1. Update a description of a prop in the input component

==> the component is replaced in the preview iframe but its documentation is not.

**Comment by elevatebart** [comment]
@znck if you have an idea how to ask vite to HMR `comp.vue.__docgen__` at the same time as `comp.vue` it would be awesome.

**Comment by znck** [comment]
I'll try to figure out something.
